### ISSUE TITLE
tag with version and latest

### ISSUE THREAD

**Issue by timwitty** [jeffreydwalter/ColReorderWithResize#1]
Hi,

Any way you may be able to create a couple tags so this script can be used with jsdelivr CDN?

It looks like you've marked this as 2.0 in the license file.

https://www.jsdelivr.com/?docs=gh

It requires at least one of these to work.

Thanks

**Comment by jeffreydwalter** [comment]
Happy to, do this work? https://github.com/jeffreydwalter/ColReorderWithResize/releases/tag/release%2F2.0

**Comment by timwitty** [comment]
Thanks for the quick action on this, unfortunately this doesn't seem to work.

It seems for jsdelivr to know which version to use it relies on the tags and uses those tags in the URI. So, since the new tag is `release/2.0`, it doesn't seem to work due to the slash most likely.

Below are some tips they give to allow it to work. Based on this, if the tag could be just `2.0.0`, I think that would allow it to work based on the examples provided on their site.

Again much thanks on the quick response and for your contribution here!

> All packages hosted on npm and **tagged releases on GitHub** are automatically available on jsDelivr. If you are a package author, here are a few tips to make using your package as easy as possible:
> 
> - Use semver for versioning (this is enforced by npm but not by GitHub)
> - If a file listed as main in package.json isn't meant to be used in a browser, set a browser or jsdelivr field
> - If you distribute minified JS/CSS files, also include source maps for those files
> - If you don't want to provide minified files, it's fine - we'll handle that for you

**Comment by jeffreydwalter** [comment]
How about now?

**Comment by MartinKolarik** [comment]
Hi guys - Martin from jsDelivr here. Any GitHub tag should work, but slashes need to be URL encoded to be interpreted correctly:

http://cdn.jsdelivr.net/gh/jeffreydwalter/ColReorderWithResize@release%2F2.0/
http://cdn.jsdelivr.net/gh/jeffreydwalter/ColReorderWithResize@2.0/

**Comment by timwitty** [comment]
Yes! that works.

Thanks for the detail Martin. I will keep it in mind for the future.
