### ISSUE TITLE
Missing comma

### ISSUE THREAD

**Issue by Martskin** [jeffreydwalter/ColReorderWithResize#10]
Somewhere in the merge of the last PR a comma was dropped after `allowResize: true`. It's causing a `Uncaught SyntaxError: Unexpected identifier` error.

https://github.com/jeffreydwalter/ColReorderWithResize/blob/master/ColReorderWithResize.js#L1620

**Comment by Martskin** [comment]
Looks like the problem was introduced here:
https://github.com/jeffreydwalter/ColReorderWithResize/commit/bdf5603bf3b04b96256fa04daefec89443038de9#diff-e6c39dd5a8cd09bff9a661112649a7e7R1618

**Comment by jeffreydwalter** [comment]
Yeah, had to manually merge your work into mine because of the whitespace
changes. I'll fix that comma later today.

Thanks!

**Comment by jeffreydwalter** [comment]
Fixed that! Sorry about it and thanks again for your help!

**Comment by Martskin** [comment]
Thanks! Glad to help.
