### ISSUE TITLE
Unable to resize not sortable columns

### ISSUE THREAD

**Issue by dpetrov** [jeffreydwalter/ColReorderWithResize#12]
Is there any constraint regarding if columns are _sortable_ or not?
I currently have a few datatables (Datatables version 1.1012), where columns with definition _**"bSortable": false**_ are not resizable as well. If I make them sortable, I can resize the tables.
Thanks

**Comment by jeffreydwalter** [comment]
@dpetrov Sorry for the long delayed response.  Can you please provide a basic example that illustrates your problem? Thanks.
