### ISSUE TITLE
Save state between client sessions

### ISSUE THREAD

**Issue by KoldoRamirez** [jeffreydwalter/ColReorderWithResize#13]
I think it would be useful to have a kind of stateSave option to save columns width and location between client sessions.

**Comment by jeffreydwalter** [comment]
@KoldoRamirez you can do that using stateSave. You just have serialize the column metadata and to persist it on the server.

**Comment by jeffreydwalter** [comment]
Another way is to turn saveState off and persist it yourself via ajax.

**Comment by e88y** [comment]
> 
> 
> Another way is to turn saveState off and persist it yourself via ajax.

could you provide a example on how to restore the columns?

**Comment by jeffreydwalter** [comment]
@e88y take a look at the dataTables documentation: https://datatables.net/reference/option/stateSave
