### ISSUE TITLE
Extra Long Words don't wrap

### ISSUE THREAD

**Issue by jemoreno** [jeffreydwalter/ColReorderWithResize#14]
Even when explicitly setting word-break: break-all the cell does not break a long string into multiple lines to adjust for the width resizing.

**Comment by jeffreydwalter** [comment]
Please provide a reproducible example so I can see what you're talking about. Thanks.

**Comment by jemoreno** [comment]
Think of using a table of redirect links (a piece of a program I am working on) and each link is extremely long because of the query string.  
![screen shot 2018-10-19 at 12 46 13 pm](https://user-images.githubusercontent.com/4119838/47234953-11fe3a00-d39d-11e8-9481-616ca365c2db.png)

**Comment by jemoreno** [comment]
What I would like to see is if it wraps the text, or possibly hides it up to a set min-width with an overflow: scroll-x kind of approach

**Comment by jemoreno** [comment]
https://jsfiddle.net/jemoreno/aq9Laaew/253804/
