### ISSUE TITLE
Add package.json so it works with npm

### ISSUE THREAD

**Issue by konuch** [jeffreydwalter/ColReorderWithResize#2]
Hello, 

could you please include `package.json` file into the repo, so we can include it in our own package.json files and install it easily using "npm install".

Thanks.

**Comment by jeffreydwalter** [comment]
Hi, please feel free to open a PR. Thanks!

**Comment by konuch** [comment]
Done #3

**Comment by jeffreydwalter** [comment]
Thank you!
